namespace DataService.Domain.Repository.Models;

/// <summary>
/// OFBiz Party: a person or group belonging to a tenant.
/// </summary>
public class Party
{
    /// <summary>
    /// Simple primary key autogenerated integer id.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// External Unique Identifier (GUID v7) of the party. Also the external id of the user.
    /// </summary>
    public required Guid PartyId { get; set; }

    /// <summary>
    /// Primary key of the owning tenant.
    /// </summary>
    public int TenantPk { get; set; }

    /// <summary>
    /// Primary key of the party type.
    /// </summary>
    public int PartyTypePk { get; set; }

    /// <summary>
    /// Identifier of the party in an external system (HR, directory, ...).
    /// </summary>
    public string? ExternalId { get; set; }

    public string? Description { get; set; }

    public bool IsActive { get; set; } = true;

    public DateTime? CreatedUTCDate { get; set; }

    public DateTime? UpdatedUTCDate { get; set; }

    public string? CreatedBy { get; set; }

    /// <summary>
    /// Custom fields stored as a JSON string.
    /// </summary>
    public string? ExtProps { get; set; }
}
