@data_service_HostAddress = http://localhost:5252

GET {{data_service_HostAddress}}/api/v1/tenant/01a01bae-7514-7958-8d3c-015e6a56b664
Accept: application/json

###

POST {{data_service_HostAddress}}/api/v1/tenant
Content-Type: application/json

{
    "name": "Retest Tenant",
    "code": "TEST007",
    "legalName": "Test Tenant 5",
    "taxCode": "TEST005TAX",
    "country": "US",
    "timeZone": "UTC",
    "locale": "en-US",
    "industryType": "IT",
    "extProps": {
      "intProp": 78,
      "decProp": 45.67,
      "strProp": "arturo",
      "arrayProp": ["12", "24"]
    }
}

### readiness

GET {{data_service_HostAddress}}/api/healtz/ready
Accept: application/json
